spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud2020?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: Admin@123